### ISSUE TITLE
Larger initial size of emojis in preview

### ISSUE THREAD

**Issue by Ryuno-Ki** [xem/unicode13#1]
Dear @xem,

would it be possible to increase the display size on https://xem.github.io/unicode13/emoji.html ?

This would require a change in

https://github.com/xem/unicode13/blob/c963257e837c25ae6d829de8a8352b5c279d64a9/emoji.html#L66

(`px` values don't respect user choice of preferred font-size in the settings. Please use `(r)em`).

**Comment by xem** [comment]
sure, updated it as 1.5rem

**Comment by Ryuno-Ki** [comment]
My eyes thank you so :older_man:
